import { TutorialPageShell } from "@/components/ui/tutorial-page-shell";
import { TutorialCodeBlock } from "@/components/ui/tutorial-code-block";

export default function FindPerformancePage() {
  return (
    <TutorialPageShell
      sectionTitle="Performance and Edge Cases"
      previousHref="/tutorial/find/historical-reads"
      previousLabel="Historical graph reads"
      nextHref="/tutorial/updating-documents"
      nextLabel="Updating Documents (CHANGE)"
    >
      <p className="mb-6 leading-relaxed text-zinc-600">
        Graph traversal and vector search do more than scan structured fields, so they have different performance characteristics. A graph query spends work resolving connected paths; a semantic query spends compute comparing vectors. Knowing where that work happens helps you write queries that stay focused and set sensible expectations for newly written documents.
      </p>

      <h3 className="mb-3 text-lg font-semibold text-zinc-900">Keep graph patterns selective</h3>
      <p className="mb-4 leading-relaxed text-zinc-600">
        A pattern may hold intermediate paths in memory as it follows bonds. In a highly connected graph, each additional hop can multiply the number of possible paths. Anchor the pattern with a selective condition so the engine can start from a smaller set of nodes and prune irrelevant paths early.
      </p>
      <TutorialCodeBlock label="Anchor a path at a specific brand">{`FIND PATTERN users AS u
  LINKED VIA "purchased" TO products AS p
  LINKED VIA "manufactured_by" TO brands AS b
  WHERE b.name = "Acme Corp"`}</TutorialCodeBlock>
      <p className="mb-8 leading-relaxed text-zinc-600">
        The brand condition narrows the destination before CleaveDB resolves full purchase paths. Apply similarly selective conditions to whichever node has the strongest useful constraint for your question.
      </p>

      <h3 className="mb-3 text-lg font-semibold text-zinc-900">Plan for semantic search to arrive after writes</h3>
      <p className="mb-6 leading-relaxed text-zinc-600">
        Semantic search depends on document vectors generated by a background worker. A SCOOP read can see a newly written document immediately, while the semantic index may take time to catch up. The search phrase is embedded and compared against the vectors, so semantic queries can also be more compute-intensive than ordinary field filtering, especially as a collection grows.
      </p>

      <h3 className="mb-3 text-lg font-semibold text-zinc-900">Be aware of graph changes during traversal</h3>
      <p className="mb-6 leading-relaxed text-zinc-600">
        Bonds can expire while background cleanup is running. The guide describes this as a possible time-of-check/time-of-use race: a bond may be observed just before its expiry cleanup runs. CleaveDB re-verifies graph paths so returned results remain structurally sound, but applications should still treat relationship results as a view of graph state at query time.
      </p>

      <aside className="rounded-lg border border-blue-100 bg-blue-50/70 p-5 leading-relaxed text-zinc-700">
        <h3 className="mb-2 font-semibold text-zinc-900">Prefer the syntax that tells the truth about the task</h3>
        <p>
          Use FIND for graph paths and semantic shorthand. Use SCOOP for structured bucket filters, analytics, sorting, and projection. CleaveDB may accept older cross-over spellings for compatibility, but new queries are easier for people to understand when each form is used for its documented purpose.
        </p>
      </aside>
    </TutorialPageShell>
  );
}
